name: null

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cmake=3.16
  - cudatoolkit=10.1
  - cudnn=7.6
  - cupti=10.1
  - cxx-compiler=1.0
  - jupyterlab=2.2
  - mpi4py=3.0 # installs cuda-aware openmpi
  - nccl=2.5
  - nodejs=14
  - nvcc_linux-64=10.1
  - pip=20.1
  - pip:
    - tensorflow-gpu==2.3.*
    - -r file:requirements.txt
  - python=3.7
  - pytorch=1.7
  - tensorboard=2.3
  - torchvision=0.8  
